### ISSUE TITLE
Play/Pause Hotkey gets triggered in MC chat

### ISSUE THREAD

**Issue by scrummer** [klauke-enterprises/ilovemusic-labymod-addon#12]
**Describe the bug**
Currently the defined play/pause hotkey gets also triggered when the MC chat is opened.

**Expected behavior**
Should not get triggered as you normally want to type text and not toggle the music.

**Tested Versions**
- `1.8.9`
- `1.12.2`

**Comment by FelixKlauke** [comment]
A hotkey is desired to work everywhere and is usually chosen from a set of uncommonly used keys. I will still implement this for chat.

**Comment by scrummer** [comment]
Have you used the Key-element module? https://docs.labymod.net/pages/create-addons/ingame_settings/#keyelement

Afaik, it should implement that behaviour.

**Comment by FelixKlauke** [comment]
This seems to implement then choosing of a new hot key in settings but doesn't implement the trigger needed to detect a used hotkey. At the moment this is implement like this:

```java
  @SubscribeEvent
  public void onTick(ClientTickEvent event) {
    toggleMusicCooldown--;
    if (toggleMusicKey != -1 && Keyboard.isKeyDown(toggleMusicKey) && toggleMusicCooldown < 10) {
      toggleMusic();
      toggleMusicCooldown = 20;
    }
  }
```

I will just add a check for an opened chat.
