### ISSUE TITLE
Lags in the addon menu

### ISSUE THREAD

**Issue by scrummer** [klauke-enterprises/ilovemusic-labymod-addon#13]
**Describe the bug**
When switching the tab to ILoveMusic or switching the channel, lags occure.

**Additional context**
This is a bug from a staff member, which I haven't tested myself. For further information you can reach out to me on Discord.

**Comment by FelixKlauke** [comment]
We're investigating here. But this is mostly relying on the speed of the API delivering the page content. I will see if we can do more async work here.

**Comment by FelixKlauke** [comment]
At the moment I will not change this. Every caching or async loading I considered would lead to inconsistent results and doesn't really improve the performance so much. The main time is consumed by the images. In trade of "live" updates, image quality and consistent results the delay will persist for first. The delay is minimal and doesn't even feel slower than any other minecraft GUI. As we couldN#t trace the origin of this bug anyways I will close this for now. Any bigger rework that could lead to better performance isn't worth at the moment.
