### ISSUE TITLE
Hotkey support

### ISSUE THREAD

**Issue by scrummer** [klauke-enterprises/ilovemusic-labymod-addon#6]
**Is your feature request related to a problem? Please describe.**
While testing the addon there were several situations where it would have been nice to have a hotkey to toggle the radio.

Therefore it would be helpful, if you add addon specific settings where you can define an optional shortcut to toggle the radio on/off.

**Comment by FelixKlauke** [comment]
Do you have any example addon where hotkeys are implemented so I can start from there for a good UX?

**Comment by scrummer** [comment]
The voicechat is a good example - the plugin settings:
![image](https://user-images.githubusercontent.com/15173170/77913076-ed95d500-7293-11ea-882b-90be993b56f9.png)

And here the Settings UI:
![image](https://user-images.githubusercontent.com/15173170/77913135-07cfb300-7294-11ea-9070-9f4db91ffe24.png)
